### ISSUE TITLE
Familiarize Ourselves with Figma 

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#1]
None of us have used Figma, but it seems like a powerful tool. At least one of us should go in and take a look around and see what it has to offer and report back here. If it is deemed useful, we can use it, otherwise, at least we know what it could be used for

**Comment by MuellMark** [comment]
I'm going to go ahead and get started with this before class so that we may be able to work together to get something planned out in Figma. I'll take the welcome tour and see what I can come up with and I'll report back with my thoughts

**Comment by MuellMark** [comment]
I've been looking around for about half an hour. I'm far from fully understanding it, but I think I am understanding the purpose of this application. It's main appeal is being able to create what the UI should look like, and how it will appear across platforms. This is especially evident, as it lets you run a simulation of your site on different platforms, as seen below: 
<img width="1284" alt="Screenshot 2024-01-30 at 7 57 08 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/92736704/ef1acf63-cd09-45b8-acb4-d310b2e3a7e1">
(obviously I'm still new to it so it doesn't look great)
This will be a great tool to help us visualize what we want the site to look like. A Couple of things I took note of: a frame is supposed to be a whole page, you can't combine 2 pages to get a longer pages. I'm also not sure if links can be put in, or buttons or anything, but there is a way to add in variables

**Comment by colbySullivan** [comment]
I started reading what and how Figma is used for in the link below. I'm unsure if we want look into finding out if converting Figma into HTML is allowed or helpful but it looks like there are a lot of instructions on how to do so.
https://www.figma.com/best-practices/guides/
https://www.figma.com/community/plugin/851183094275736358

**Comment by colbySullivan** [comment]
After looking into the possible ways that we could incorporate the code from the original repository #3 I looked into seeing if we could do the same with Figma. I'm unsure if this is exactly what we want to do but it is possible to import the work from Figma into this GitHub or another smaller one that we can use for reference. The pros of doing this would be a more streamlined version control and we could also incorporate branches so we can split up the design sections.
https://www.emulsify.info/docs/systems/ui-kit/connecting-figma-to-github

**Comment by Hamdally** [comment]
I am watching videos about how to use Figma as I have heard about it from other students and alumni. I am unsure of all of its features and purpose, so I think this is a good starting place.

https://www.youtube.com/watch?v=JGLfyTDgfDc

**Comment by Hamdally** [comment]
> I am watching videos about how to use Figma as I have heard about it from other students and alumni. I am unsure of all of its features and purpose, so I think this is a good starting place.
> 
> https://www.youtube.com/watch?v=JGLfyTDgfDc

This tutorial was extremely helpful for getting the basics of figma down. I will be working on a mock-up version of the "Add Course Information Form" page. Will continue on this to get more familiar with figma while also getting an idea of what our final product might look like.

**Comment by MuellMark** [comment]
I'm also closing this because at this point anything that we do in figma should be in regards to making our prototype in #6
