### ISSUE TITLE
Revise existing CSV requirements for Database

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#12]
As we start integrating the python code into an html page, it's important to look into all considerations for what the CSV files may need and revise them accordingly. I'm going to compile a list of different options that we can discuss formally whenever we meet up again.

**Comment by MuellMark** [comment]
There needs to be some functionality for having the full name of courses be listed. While we could have a python enumeration handle this, I think it would make a lot more sense to have a database as it would be more secure, and more comprehensive than a python script or txt file. Everything that should be incorporated is as follows:

1. A primary key which is increments automatically
2. The full name of the course, for displaying on the site
3. the 4 letter abbreviation for the python code
Those are the absolute necessary things we need, but we could add more such as descriptions and course ID's from the university itself.

I'm mainly suggesting a database as it can be integrated into the drop down box for our CSV builder. Then, when a new one is added, it can be added into the pool to be reused later. This could even be specific to each user.

Other modifications we could make is altering the 4 letter abbreviations for the courses in the python code itself. This isn't impossible, but it would be an inconvenience, especially if we are going with a database.

I know there are python scripts that can handle database connections (I have been messing around with them in my personal project), but I know that java and js are more suited to do this. This works out because I have a bit of experience with that in my internship. Either way, it would be a great idea and we'll discuss this more when we meet

**Comment by katenguyen10** [comment]
Based on these requirements, I am going to write out some specific database tables so that we see all of the requirements for the courses and the relationships between them. I will post that here when I am done

**Comment by katenguyen10** [comment]
After about 40 minutes, I’ve created the faculty and course tables, as well as a cross reference table for the specific sections of the courses, with foreign keys that reference the faculty member teaching it and the course it is.
![EA773654-4A82-4F25-878C-15FD24541A1A](https://github.com/MuellMark/Course-Scheduler/assets/89275901/833049b1-87d3-43a2-93ed-d61809217612)

**Comment by katenguyen10** [comment]
Here are the tables I’ve made based on Mark’s requirements. We will obviously meet and discuss whether more are necessary or if changes need to be made. This initial structure allows specific calls to faculty and course information easily through some simple database statements. 
![Uploading 1A802917-B93F-438F-86E5-3C613FCEA8FF.jpeg…]()

**Comment by MuellMark** [comment]
TODO: remove the num_sections from the course table, and replace it with the university course number. We'll focus on the first 3 tables at first, then we can try and incorporate the other two if we have time and everything works. We should also add in a column for the year and semester, especially for the schedule display

**Comment by MuellMark** [comment]
After looking through this thread, I realized that much of this was planning for the database we're adding in. Because #23 is going to be the central hub for DB related issues, I'm closing this issue and opening a new one that's specific to revising CSV formats for the python code itself
