### ISSUE TITLE
Design Ideas/Mock-Ups For Webpages

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#15]
This issue will propose design ideas and mock-ups that we can give feedback or ideas to.

**Comment by Hamdally** [comment]
I have been working on a mock-up for the "Add Course Information Form" Webpage. I am still very much in the early stages as I am still figuring out buttons and dropdown menus. But the webpage should be functioning with animations to show what we are thinking.

 
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/7cd72e6a-4543-4b4d-b33b-87cdc0edd88c)

**Comment by Hamdally** [comment]
> I have been working on a mock-up for the "Add Course Information Form" Webpage. I am still very much in the early stages as I am still figuring out buttons and dropdown menus. But the webpage should be functioning with animations to show what we are thinking.
> 
> ![image](https://private-user-images.githubusercontent.com/88158644/303939624-7cd72e6a-4543-4b4d-b33b-87cdc0edd88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzY3MzIsIm5iZiI6MTcwNzY3NjQzMiwicGF0aCI6Ii84ODE1ODY0NC8zMDM5Mzk2MjQtN2NkNzJlNmEtNDU0My00YjRkLWIzM2ItODdjZGMwZWRkODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE4MzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWJmNTcxZGZkMDM0ZDJlYTY5ZWQ1Yjg3MWYwMjgwMGNjMTk1N2Q2NGMzZjc3OGJmY2YwZGJiNzE4NDg4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dq0ADbvEyHg-lvZwR2jIJTmYiGZOKiFwomLEW6vbC_Q)

I am still working on it; I created a new task in #13 to figure out how to make buttons interactive, as I want to make it so that once you click on Create Course, the rest of the options appear.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ebd24489-e98b-4f65-a80c-acdd36ad334c)

**Comment by Hamdally** [comment]
> Time: 12:30 PM
> 
> I have been working on a mock-up for the "Add Course Information Form" Webpage. I am still very much in the early stages as I am still figuring out buttons and dropdown menus. But the webpage should be functioning with animations to show what we are thinking.
> 
> ![image](https://private-user-images.githubusercontent.com/88158644/303939624-7cd72e6a-4543-4b4d-b33b-87cdc0edd88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDE4MjYsIm5iZiI6MTcwNzcwMTUyNiwicGF0aCI6Ii84ODE1ODY0NC8zMDM5Mzk2MjQtN2NkNzJlNmEtNDU0My00YjRkLWIzM2ItODdjZGMwZWRkODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAxMzIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWY3ZGRlOGQ5MzE0NmYwZjBjZmFjZjhlMGM3NDhmNGQwOWRhYmI4OWFkZmI2NDkzZGRlYWZkMjJjZTE1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.an7_qX2sXGmsgw8_A1IRJJQrg7_BHVrCPt6F77AwztE)

Time: 7:32

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ed6a2be3-3766-4437-af2b-0bbdb8b8ddd1)

Progress for design and button/drop-down menu task. Cleaning up design and incorporating the previous design from Mark.

**Comment by Hamdally** [comment]
Starting work on FAQ Page. Is there anything specific we want on this page? Or just questions and answers? @colbySullivan  @MuellMark @katenguyen10 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/49baab7b-73c2-4b76-a20b-5ff2302b0c0e)

**Comment by Hamdally** [comment]
Working on Design for Home webpage

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ee6abb62-9853-4d74-8cff-c62bdb300877)

**Comment by colbySullivan** [comment]
@Hamdally Although its not a frequently asked question I remember the main thing we discussed was implementing how to use guide. That will have to come way later when we have a working copy. We could also put the GitHub button in there instead of having it on the main page.

**Comment by Hamdally** [comment]
Based off the crash course video, issues #24, I decided to change up the design a little bit as HTML is very tedious. Here, you will see that instead of the web page options below the image, there will be a navigation bar with the webpages. This will make the code simpler, but also, more clean. You will see below what I mean. 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/01380d03-3049-4f77-876e-0b31162f3bf8)

**Comment by Hamdally** [comment]
Closing out this issue as design mock-ups are complete.
