### ISSUE TITLE
Database table creation and explanation

### ISSUE THREAD

**Issue by katenguyen10** [MuellMark/Course-Scheduler#16]
I made a basic layout of the basic necessity database tables we will need for our course and faculty information. I am going to make a document explaining each field and its functionality. I will also write a few simple database statements to retrieve specific data to show how they can be implemented in our website. I will put this in the Google Drive folder so everyone has access as well as posting a link here: https://docs.google.com/document/d/19wlKb1K-jiw4wtwa24djKZKZ_pXIfE3KMsnCNb_i-bU/edit

**Comment by katenguyen10** [comment]
After 45 minutes, I have written descriptions for each table, that can be seen in the Google Doc explaining its field/functionality. I will now work on writing some database statements to show how to access the data that we will use for our website.

**Comment by katenguyen10** [comment]
After another 30 minutes, I have written a few database statements that can be used to access some data that would be used to display certain information in our website, such as retrieving all sections of a course, courses that a specific faculty member is teaching, etc. All of these can be seen in the google doc I made called database tables in the drive.

**Comment by MuellMark** [comment]
After consulting with Kate, we've both agreed that this issue is complete and anything that will reference the database will be either made in #23 or in other issues.
