### ISSUE TITLE
Find the Optimal Way to Call a Python Script from HTML

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#18]
As mentioned in #2, I've found that pyscript will work to call a python script, I just need to look into the best way to integrating it into the site.

Ideally, this could be done in pyscript, but js and php are also options I'm willing to explore

**Comment by colbySullivan** [comment]
I saw what you pushed into the main branch and I tried to expand on it. I'm experimenting with running a separate python script using pyscript as well but I'm also trying to pass arguments through it. I'll push it into main when I get it working.

**Comment by colbySullivan** [comment]
I'm a little late on this update but I've trying to getting the values from the html form to pass as arguments. The main issues I've been running into have to deal with the virtual file system that is setup but it won't recognize my script file.

**Comment by colbySullivan** [comment]
I've been working off and on for the last hour so I'll just leave it all in this comment. I created a working prototype for calling python functions through a virtual environment and I also found a new way to host a local website through VS Code. I have attached the VS Code plugin down below. As for the python script, I got the form values to pass through the script but I have not gotten them to save on a webpage refresh so only the drop down name has a value.
![image](https://github.com/MuellMark/Course-Scheduler/assets/88957296/659777b7-afaf-4216-856b-c3af487ab08d)
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by colbySullivan** [comment]
I found a temporary fix to saving values after submitting. I got the Select and Add course boxes to accurately pass values from the HTML form to the python script. I'm going to clean it up a little more to make it easier to read and then I'm going to merge the branch.

**Comment by colbySullivan** [comment]
I started experimenting with looping through a simple csv file for the course list. Then I'll try and fix the checkbox issue that I have been having. It always passes as true even if it is unchecked. Other than that I've got everything passing except the last 3 sections on the form.

**Comment by colbySullivan** [comment]
Finally got the CSV file to be read into the script but I had to do a workaround. Unlike the printing of the user inputs the csv file has to be read into the HTML file's virtual file system which apparently is different from the python file's virtual file system. I am working on adding the values from the CSV into the drop down form question.

**Comment by colbySullivan** [comment]
I couldn't quite get the drop down menu to work but I left in some extra documentation if anyone wants to try as well. I think its in a good enough state to push the prototype into main.

**Comment by Hamdally** [comment]
We are going to go ahead and close this out as it seems inactive and we have started to get more results.
