### ISSUE TITLE
Hosting Flask App

### ISSUE THREAD

**Issue by colbySullivan** [MuellMark/Course-Scheduler#212]

**Comment by colbySullivan** [comment]
I am going to start and revisit our idea of hosting of application on a Linux server through a raspberry pi.

**Comment by colbySullivan** [comment]
I have the server running on two separate distros of Linux (Arch and Debian) but the same GLPK issue is still happening.

**Comment by colbySullivan** [comment]
I got it working on my local machine and on my local network but now I need to set up Apache so everyone can access it.

**Comment by colbySullivan** [comment]
I have switched gears and decided to use gunicorn as I am more familiar with and it seems to be going more smoothly thus far.

**Comment by colbySullivan** [comment]
I have gotten the gunicorn server up and running but I am trying to configure it to my ip rather than our domain since we don't have one yet.

**Comment by colbySullivan** [comment]
It is quite messy on my desk but I currently have a Raspberry Pi running an ubuntu server for our Flask application. That was a lot of weird words back to back but the pros are we can now work on the script outputs without needed a third party services for now. The only drawbacks are you can only access it from my home WiFi as I couldn't get the ports to open with a domain.

**Comment by colbySullivan** [comment]
I am signing of for now but I got a decent optimal script output page. But it is a little finicky to work with as it requires you to restart the server for the changes to take effect. I will touch base with our front end about it tomorrow.

**Comment by colbySullivan** [comment]
For the last thirty minutes I have been fixing all the settings in pythonanywhere so it will run more smoothly. I have changed the working and source directory so it will recognize files easier. I have also deleted some redundant files so it is easier to read.

**Comment by colbySullivan** [comment]
I have gotten the next button to streamline the data to the database. I am now working on skipping the import CSV page all together.

**Comment by colbySullivan** [comment]
I have given up on getting Javascript to pass values to the Flaskl. It requires ajax which I tried to set up but I don't think we have enough time to effectively do so.

**Comment by colbySullivan** [comment]
I have gotten part of the swap table to work correctly. I am going to work for another 30 minutes and then take a break till tonight.

**Comment by colbySullivan** [comment]
I got the swap course table to fill out dynamically and I got all the times mapped out correctly. It is also passing the values correctly to the swap function. I plan on meeting with Mark later tonight to connect the two.

**Comment by Hamdally** [comment]
We got out flask app to work and is running on Python Anywhere. This issue is not needed anymore.
