### ISSUE TITLE
Presentation Slides 

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#214]
This issue will be used for our slides.

[SLIDES](https://docs.google.com/presentation/d/18dp5Hfg7fhe0X1O_hGzmYavI0MeBieiFDJ8IkM4mPQ4/edit?usp=sharing)

**Comment by Hamdally** [comment]
We can mostly rely on our poster for details, but we need to expand more on the front end, and other aspects of the project like effort and time. 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/a52759eb-172b-4a8d-bd44-1a3cfc66da36)

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ec7231c8-1c78-405b-9a28-b3481497a9e8)

**Comment by katenguyen10** [comment]
coming back to this, going to shorten slides to just small bullets we will elaborate on

**Comment by katenguyen10** [comment]
After 30 minutes I have been working on the slides, moving the long info away and putting speaking points

**Comment by katenguyen10** [comment]
After 30 minutes I am still working on the slides

**Comment by katenguyen10** [comment]
Coming back to keep working

**Comment by katenguyen10** [comment]
After 30 minutes, I am continuing to work on the presentation

**Comment by katenguyen10** [comment]
Still working after another 30

**Comment by katenguyen10** [comment]
coming back to continue

**Comment by katenguyen10** [comment]
After 30 minutes I have added a slide about ongoing work if we think that is necessary and adding some small bullets that we will elaborate on in our speech

**Comment by katenguyen10** [comment]
For the past 45 minutes, I was looking at previous years capstones to see any other important information to include in the presentation as well as continue making edits to our own.

**Comment by MuellMark** [comment]
I said I'd work on the slides in #240, but I was mostly just doing tests on the page to make sure everything is working. So far, I don;t see any issues so I feel more confident for a live demo.

I'll start working on the slides after I eat something

**Comment by MuellMark** [comment]
I'm going to work on my parts of the slides now

**Comment by MuellMark** [comment]
I started adding to my slides, but I;m running out of steam and I'm going to complete everything else tomorrow, either in class or before.

**Comment by Hamdally** [comment]
Slides have been completed and the presentation has been given. This issue is not needed anymore.
