### ISSUE TITLE
Creating a database

### ISSUE THREAD

**Issue by katenguyen10** [MuellMark/Course-Scheduler#23]
I am looking into how to set up a database for us so that we can create tables and add test data. It will also be used by Colby who is attempting to connect a database to the webpage

**Comment by katenguyen10** [comment]
For the past 30 minutes, I have been downloading MySQL and MySQL workbench and am working to establish a new connection. It is currently not working and I am running into similar issues that I had with Mark in class but will keep researching how to set it up

**Comment by katenguyen10** [comment]
For 30 minutes I have been looking into easier ways to create and connect to a database and I think an Oracle cloud database would be a good one. Especially if this is just for testing and such. It creates a connection and new database that any of us can access from anywhere. I used them in my internship this past summer and think it could be useful. Here's a link about them: https://www.oracle.com/database/what-is-a-cloud-database/

**Comment by katenguyen10** [comment]
For about 45 minutes, I have created an autonomous transaction processing database in Oracle Cloud Infrastructure (OCI) and am working to establish a connection to it on my device. Here is a resource I found that explains what it is: https://www.oracle.com/autonomous-database/autonomous-transaction-processing/

**Comment by katenguyen10** [comment]
It has been 30 minutes and I have created the connection to the database on my machine. Trying to figure out now how to add other users to access it.

**Comment by katenguyen10** [comment]
After 45 minutes, I found out how to add other users to the cloud database. I will show everyone how to do it during project work time in class. I am currently figuring out how to access sqlplus from MobaXTerm.

**Comment by katenguyen10** [comment]
It's been about 45 minutes and I am still running into issues when trying to connect to sqlplusat the command line. I checked my wallet download, the connection string and tns name are correct, and I created a user for myself. However, it keeps providing me with the usage help message from sqlplus which usually indicates a syntax error of some sort. I am using what it provides me, but to no success so far.

**Comment by katenguyen10** [comment]
For the past 30 minutes, I have been creating the tables we discussed in issue #12. I am creating them in oracle sql developer for now until I can figure out how to connect through MobaXTerm

**Comment by katenguyen10** [comment]
After 30 minutes, I have finished creating the course, faculty, and course/faculty cross reference tables. The cross reference table contains foreign key values referencing the specific course associated with a section of it, as well as the faculty member teaching it. I added the semester and year columns as well to accomodate the possibility of faculty changes each semester.

**Comment by katenguyen10** [comment]
For 30 minutes, I have added some test data into the tables. This will also be helpful for Colby to use when he attempts to connect the database to the webpage.

**Comment by colbySullivan** [comment]
Going to start working on connecting the database to a simple view page that we have in the src file.

**Comment by colbySullivan** [comment]
I think I have the main outline correct but I ran into an issue where PHP did not recognize the connect command. I attached the relevant link below. I am also currently working on MacOS but I will try to connect through a window machine when I get home.
https://stackoverflow.com/questions/22478387/call-to-undefined-function-oci-connect

**Comment by colbySullivan** [comment]
I have attempted to install sqlplus on my personal machine with some promising results. I have attached both of the sources below that I used to get it installed. Now I will attempt to fix the issue with PHP where it can't find the sqlplus connect method.
https://developers.ascendcorp.com/how-to-install-oracle-instant-client-on-apple-silicon-m1-24b67f2dc743
https://www.geeksforgeeks.org/how-to-install-sqlplus-on-macos/

**Comment by katenguyen10** [comment]
We were running into some issues with the Oracle database connection with PHP, so we are going to take a different direction and I am going to look into Firebase.

**Comment by katenguyen10** [comment]
After 30 minutes, I have done some research into Firebase. I found it is a NOSQL cloud database that uses data synchronization versus HTTP requests. There is no need for an application server to access the database, it can be accessed directly through a mobile device or web browser. I think this will be very helpful for us. I created a google doc that has my findings, I put it in the shared drive. Here is a link to it as well that I will keep adding to: https://docs.google.com/document/d/1iOlebJ-m8qi93Yb-S6TLQv0294YXVYrLSNdaE3W4rfo/edit

**Comment by katenguyen10** [comment]
After 30 more minutes I kept researching about it and found this good overview video that I found helpful. I will now follow the steps in it to set a Firebase database up for us. 
Link to video: https://www.youtube.com/watch?v=pP7quzFmWBY

**Comment by katenguyen10** [comment]
After 35 minutes, I have created the database and am exploring the Firebase console to familiarize myself with it.

**Comment by katenguyen10** [comment]
After 45 minutes I watched these videos to help me understand adding tables, rows, and values into the database and integrating the database which Colby might find helpful/connecting Python application to it. Then I started creating the structure of the course, faculty, and course_faculty tables. 
1.) https://www.youtube.com/watch?v=qKxisFLQRpQ 
2.) https://www.youtube.com/watch?v=fI1bxMKMY5g
3.) https://www.youtube.com/watch?v=BnrkTpgH5Vc (connecting python app to Firebase)

**Comment by katenguyen10** [comment]
30 minutes and I have created the structure of the data. I am researching how to add actual data/make physical tables vs just the structure of them

**Comment by katenguyen10** [comment]
So far, after 30 minutes, I have only figured out how to add them in manually in Firebase, but it requires me to individually add one row at a time which is inefficient. Trying to figure out if there is an easier way to do this.

**Comment by katenguyen10** [comment]
After 45 minutes, I have not figured out how to do this, so I will discuss with my group mates who may be more familiar with this topic. I started finding resources and watched a video to connect the database to an HTML form: https://www.youtube.com/watch?v=RAWHXRTKTHw

**Comment by katenguyen10** [comment]
After 30 minutes, I have started working on the to do list for HTML pages that Yahya and I are working on. I am coming up with FAQ questions and a description for the course scheduler.

**Comment by katenguyen10** [comment]
Link to our Firebase database: https://course-scheduler-b4f7e-default-rtdb.firebaseio.com/

**Comment by colbySullivan** [comment]
I am going to start looking into how to use Firebase from the links above and researching how to connect it to our existing files.

**Comment by colbySullivan** [comment]
I found a great source for setting up a web application using Firebase. I have gone through a couple of the steps and will update my branch with the testing.
https://www.geeksforgeeks.org/create-a-website-using-html-css-and-javascript-that-stores-data-in-firebase/

**Comment by colbySullivan** [comment]
I've followed all of the steps in the link above and I got it to write to the database given the example that was provided. I also set up a test storage in Firebase that we can use to test without using our tokens. I also started to research on how to read data from Firebase and I attached the link down below. It is the official Firebase documentation which also attaches some examples that are in GitHub. I am going to take a break for now but I will look into this more tonight.
https://firebase.google.com/docs/database/web/read-and-write#web-namespaced-api

**Comment by katenguyen10** [comment]
For 30 minutes, I have been writing the documentation for setting up a Firebase Realtime database that will be helpful for our users if they need to do this. Here is a link to it: https://docs.google.com/document/d/1A6Z0__bGbd6p0pUnr626Lgsoz3PcOo-vfHJaAMl_uOM/edit?usp=sharing

**Comment by katenguyen10** [comment]
For 30 more minutes, I have been finishing up the documentation and am going to work on the frontend design with Yahya

**Comment by colbySullivan** [comment]
I closed this to clean up the issues page and I believe we have decided on using Firebase.
