### ISSUE TITLE
Refamiliarizing With HTML and CSS 

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#24]
This is mostly for me, but I think it might also be helpful for the group, especially @katenguyen10 (as we both are doing front end), to get a basic idea of what I am doing and how you can incorporate both sides (front and backend) together. I also just need a quick refresher, which is why I chose this crash course. After this, I will continue to work on updating the template for the webpage, which will make it easier to complete the rest of the webpages. If you have any questions about what I am doing, or my code, just ask!

https://www.youtube.com/watch?v=qz0aGYrrlhU

**Comment by Hamdally** [comment]
Just coming back after 30 minutes, tutorial is extremely helpful and have been learning new things that I didn't before, I will check in at the end of the video (around 30 minutes left) and will then work on webpage.

**Comment by Hamdally** [comment]
Okay! Overall, very helpful. I think I am more confident now to get the home page done and start working on a template so we can start making other webpages.

**Comment by Hamdally** [comment]
I forgot to include this here, but this website and this starter guide for CSS is amazing! I also forgot to include the links to my references for the website, so I will do so in my code as comments. 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox

**Comment by MuellMark** [comment]
After talking with Yahyah, they have said they are done refamiliarizing with HTML and CSS!
