### ISSUE TITLE
Explore original script source code

### ISSUE THREAD

**Issue by colbySullivan** [MuellMark/Course-Scheduler#3]
The script was written by Mark Mueller so the rest of us need to familiarize ourselves with it so we can work towards integrating it into the website.

**Comment by colbySullivan** [comment]
I've been messing with the original script for the last half hour or so. I pulled it onto my personal machine so I make sense of how to use it without the interface. I think I've got a better understand but I still have a couple of question when we get back to class. Since this issue is about familiarizing ourselves with it I haven't gone too much into the process of importing it since that is issue #4.

**Comment by katenguyen10** [comment]
I too went through Mark's original script to get a better understanding of how it works. Going to continue researching about how to import the code into the website
