### ISSUE TITLE
Webpage Design and Updates 

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#33]
Here is my new Issues ticket that will help everyone stay up-to-date on what I am doing and what I plan to do. This will also be helpful for @katenguyen10 as we will both be focusing more on the front-end from here on out.

**Comment by Hamdally** [comment]
Current Tasks: 

Create CSV Page: (Yahya & Kate) 

- Make a delete row button with functionality
- Limit how many course rows can be added
- Change check box to include name of the day of the week for unavailable times
- Clean up design
- Make it look nicer
- Spread out to fit webpage
- Remove back button


FAQ Page: (Kate)
- Come up with questions and answers

Home Page: (Kate)

- Come up with description
- Add picture example
- Link github icon


Other: (Yahya & Kate) 

- Remove ‘create course schedule’ navigation
- Create page but have it be navigated to from the create csv page, not navigated to
- Create about/how to page
- Hamburger nav list on side

Things to do outside of webpage:
- Add to database
- Yahya teach how to download php stuff

**Comment by Hamdally** [comment]
Slowly working through my tasks, but here are the updates

Current Tasks:

Create CSV Page: (Yahya & Kate)
- Limit how many course rows can be added
- Change the check box to include the name of the day of the week for unavailable times
- Clean up design
- Make it look nicer
- Spread out to fit the webpage
- Make a clear option

FAQ Page: (Kate)
- Come up with questions and answers

Home Page: (Kate)
- Come up with a description
- Add picture example
- Link GitHub icon

Other: (Yahya & Kate)
- Add to database


Completed Tasks:
- Create page but have it be navigated to from the create csv page, not navigated to
- Create about/how to page
- Hamburger nav list on side
- Remove ‘create course schedule’ navigation
- Yahya teach how to download php stuff
- Remove back button
- Make a delete row button with functionality

**Comment by Hamdally** [comment]
I am slowly working through my tasks, but here are the updates

Current Tasks:

Create CSV Page: (Yahya & Kate)
- Change the check box to include the name of the day of the week for unavailable times
- Clean up design
- Make it look nicer
- Spread out to fit the webpage


FAQ Page: (Kate)
- Come up with questions and answers

Home Page: (Kate)
- Come up with a description
- Add picture example
- Link GitHub icon

Other: (Yahya & Kate)
- Add to database

Completed Tasks:
- Create page but have it be navigated to from the create csv page, not navigated to
- Create about/how to page
- Hamburger nav list on side
- Remove ‘create course schedule’ navigation
- Yahya teach how to download php stuff
- Remove back button
- Make a delete row button with functionality
- Make a clear option
- Limit how many course rows can be added

Currently working on:
Create CSV Page: (Yahya & Kate)
- Clean up design
- Make it look nicer
- Spread out to fit the webpage

**Comment by Hamdally** [comment]
> I am slowly working through my tasks, but here are the updates
> 
> Current Tasks:
> 
> Create CSV Page: (Yahya & Kate)
> 
> * Change the check box to include the name of the day of the week for unavailable times
> * Clean up design
> * Make it look nicer
> * Spread out to fit the webpage
> 
> FAQ Page: (Kate)
> 
> * Come up with questions and answers
> 
> Home Page: (Kate)
> 
> * Come up with a description
> * Add picture example
> * Link GitHub icon
> 
> Other: (Yahya & Kate)
> 
> * Add to database
> 
> Completed Tasks:
> 
> * Create page but have it be navigated to from the create csv page, not navigated to
> * Create about/how to page
> * Hamburger nav list on side
> * Remove ‘create course schedule’ navigation
> * Yahya teach how to download php stuff
> * Remove back button
> * Make a delete row button with functionality
> * Make a clear option
> * Limit how many course rows can be added
> 
> Currently working on: Create CSV Page: (Yahya & Kate)
> 
> * Clean up design
> * Make it look nicer
> * Spread out to fit the webpage

I have been working on this for the past 30 minutes, updating code and updating css and html. Committing my changes and calling it for now.

**Comment by katenguyen10** [comment]
For the past 15 minutes I have been downloading all PHP stuff required and am documenting the steps that may be helpful for others and simply for documentation purposes.

**Comment by katenguyen10** [comment]
Need to make create csv page more organized. To dos:

1. Organize it as a table to keep rows apart
2. Center buttons
3. Update heading text
4. Change checkboxes to say specific days/times

**Comment by Hamdally** [comment]
For the past 30 minutes,I have been trying to figure out how to make drop-down menus like this for our FAQ page. 

Looking at this page as a reference and this YouTube video as inspiration for code: https://www.youtube.com/watch?v=IcyXS9aL4bs

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/f1eb8980-7822-4b34-a5cf-e4ee1dcc6386)

**Comment by Hamdally** [comment]
> For the past 30 minutes,I have been trying to figure out how to make drop-down menus like this for our FAQ page.
> 
> Looking at this page as a reference and this YouTube video as inspiration for code: https://www.youtube.com/watch?v=IcyXS9aL4bs
> 
> ![image](https://private-user-images.githubusercontent.com/88158644/309498151-f1eb8980-7822-4b34-a5cf-e4ee1dcc6386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MTA1NjIsIm5iZiI6MTcwOTQxMDI2MiwicGF0aCI6Ii84ODE1ODY0NC8zMDk0OTgxNTEtZjFlYjg5ODAtNzgyMi00YjM0LWE1Y2YtZTRlZTFkY2M2Mzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIwMTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWM3OGZjYjQ4YTFmN2UwYjBkZWRiYWQ0YzBlY2ViNGFjZjI3N2VhN2IwMjQ5MTI4YzRlZjk1N2VjZWFlYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVoDxmvzGBkHmmKPXsIIMCd_OL1wlf2_84eYh96zcLw)

I have been working on this for the past 30 minutes. There is still a lot more to go, as I need to change the code a lot from the video, but will get there.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/1a4d1ac2-d469-402d-8783-4e9ddfdf3566)

**Comment by Hamdally** [comment]
Coming alone, updating the design, and making it more aesthetically appealing by adding a container and changing colors.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/4919baba-ef14-4f1c-a8f9-597c5086bfa7)

**Comment by Hamdally** [comment]
Finished for now, here is my current status on the page. There are still a couple of updates I need to do, and I need to comment code, but the foundation is there. If we want this feature on other pages, we can do it.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/89bdd477-86e0-4c45-82f1-f993fa70d723)

**Comment by Hamdally** [comment]
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ad518e92-6f79-44e8-82ef-e211ac2097b6)

For the past 30 minutes, I have been updating the design of the FAQ page and will continue to do so. As well, I am commenting to code to keep up with documentation.

**Comment by Hamdally** [comment]
I did not realize how much I forgot to comment while I was doing, so that is what I have been doing for the past 30 minutes, and removing redundant code is not necessary. I will update in the next 30 minutes.

**Comment by Hamdally** [comment]
For the past 30 minutes, I have been finishing up comments, updating naming conventions, removing redundant code, and fixing spelling mistakes. Pushing to main now so everybody else can have the changes as well.

**Comment by Hamdally** [comment]
_Updated list of current tasks @katenguyen10 :_

**Current Tasks:**

_Create CSV Page: (Yahya & Kate)_
Change the check box to include the name of the day of the week for unavailable times
Clean up design
Spread out to fit the webpage
Organize it as a table to keep rows apart
Center buttons
Update heading text
Change checkboxes to say specific days/times

_FAQ Page: (Kate)_
Come up with questions and answers

_Home Page: (Kate)_
Come up with a description
Add picture example
Link GitHub icon

**Currently working on:**

_Create CSV Page: (Yahya & Kate)_
Clean up design
Make it look nicer
Spread out to fit the webpage

**Completed Tasks:**
Create page but have it be navigated to from the create csv page, not navigated to
Create about/how to page
Hamburger nav list on side
Remove ‘create course schedule’ navigation
Yahya teach how to download php stuff
Remove back button
Make a delete row button with functionality
Make a clear option
Limit how many course rows can be added

**Comment by Hamdally** [comment]
My laptop ending up dying, but right now, I am moving onto the home page and for the past 30 minutes, have been trying to complete the tasks below. Trying to think of best way to add the icon image, which is why it is so big. 

Home Page: 
Come up with a description
Add picture example
Link GitHub icon

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/c0242604-42bf-4227-90ee-e9ba420c5bb6)

**Comment by Hamdally** [comment]
> _Updated list of current tasks @katenguyen10 :_
> 
> **Current Tasks:**
> 
> _Create CSV Page: (Yahya & Kate)_ Change the check box to include the name of the day of the week for unavailable times Clean up design Spread out to fit the webpage Organize it as a table to keep rows apart Center buttons Update heading text Change checkboxes to say specific days/times
> 
> _FAQ Page: (Kate)_ Come up with questions and answers
> 
> _Home Page: (Kate)_ Come up with a description Add picture example Link GitHub icon
> 
> **Currently working on:**
> 
> _Create CSV Page: (Yahya & Kate)_ Clean up design Make it look nicer Spread out to fit the webpage
> 
> **Completed Tasks:** Create page but have it be navigated to from the create csv page, not navigated to Create about/how to page Hamburger nav list on side Remove ‘create course schedule’ navigation Yahya teach how to download php stuff Remove back button Make a delete row button with functionality Make a clear option Limit how many course rows can be added

I have finished the github icon link. I am currently working on the homepage, but I think I broke it! So back to adjusting the CSS to make it look nicer and fix my issue.

Home Page: (Kate)
Fix design 
Add picture example

Completed:
Link GitHub icon
Come up with a description
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/fe1473fd-6111-4048-8fa6-60ce12f61aa8)

**Comment by Hamdally** [comment]
I have updated the homepage to be more aesthetically pleasing and added a description for now that we can use until we decide on a more descriptive one. I fixed my issue before on breaking the css and decided to center the text more towards the center of the page. Next, I will update the rest of the webpages code to match the same aesthetic as this one. 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/d2bd9c6a-93ff-4187-a5a0-85cd739f71da)

**Comment by Hamdally** [comment]
All webpages have been updated with a new style and I have been taking out more redundant code and fixing css to make sure each webpage can utilize it. 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/124dd3e8-3f15-45be-b18e-9602b7ff5534)
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/99932b50-2349-4db2-a7a1-287953a251e4)
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/2725cb82-2ee6-46ce-97f7-e286f8f3b3ec)
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/bbd1d360-3fab-4105-ba77-b9e84ffe9798)

**Comment by katenguyen10** [comment]
for 30 minutes I have been researching how to implement dynamically adding and deleting rows for a table in html for our create csv page

**Comment by katenguyen10** [comment]
For 35 minutes I have been updating the design of the create csv page. I created tables for the data to make it easier to see the data in a more organized way. Going to see how to change the add column button to add them vertically instead of horizontally. 
![Screenshot 2024-03-03 201544](https://github.com/MuellMark/Course-Scheduler/assets/89275901/b821aa36-b517-4749-ba0d-77316e030f3e)

**Comment by katenguyen10** [comment]
After 30 minutes, I have added to the table some buttons, need to move their functionality from the others. Been researching how to change the checkboxes.

**Comment by Hamdally** [comment]
Closing this out for now, but if we need to reference our previous work, it will be available.
