### ISSUE TITLE
Integrate Original Source Code

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#4]
Must be done before #3 can be started. I have the source code in a separate repo, but it still needs to be finalized before I can start bringing it over here. That being said, it's a python script, so if we can create a website that allows us to run a python script, then we can go from there, this should not hold up any of the front end development, unless all of the front end is complete

**Comment by colbySullivan** [comment]
I started looking into the different methods that we could possibly incorporate the existing code into this new tool. The main method that I am familiar with is repository referencing which I have attached a forum link below. If we got it working like this then we could modify the original while keeping the new updated seamlessly. The only issue that may arise is this repo is public and the other one is private.
https://gist.github.com/martinbuberl/b58fd967f271f32f51f50aee62e7332c

**Comment by colbySullivan** [comment]
Another way that could implement the original script is adding it as a submodule. I have attached the document page that we can reference. I also create a new branch so we could experiment with it.
https://github.blog/2016-02-01-working-with-submodules/

**Comment by MuellMark** [comment]
I'm marking this issue as resolved as I've already added in the source code and I'm editing in #22. The ideas on integrating the whole other repo is interesting, but because there's only one file needed, I don't think this is necesarry.
