### ISSUE TITLE
Improve readability of code through good techniques and documentation

### ISSUE THREAD

**Issue by colbySullivan** [MuellMark/Course-Scheduler#5]

**Comment by colbySullivan** [comment]
I added the restriction labels that we made in our last meeting as a comment to each of the form attributes.

**Comment by MuellMark** [comment]
I just went ahead and altered all of the tags so instead of using vague ones like "enhancement" and "design", we'll be using what aspects of the project we're working on, specific to python, webpage and DB, with learning being there to denote that it's a starter issue

**Comment by Hamdally** [comment]
This isn't being used anymore, so I will go ahead and close out this issue. If needed, we can reopen.
