### ISSUE TITLE
Create a proper Prototype in Figma

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#6]
This issue is dedicated to creating the actual prototype in Figma for our webpage. This is different than #1, which should focus on learning Figma. I'll get started by creating a base for what the site could look like, which we can then edit and add links to make it all work together.

**Comment by MuellMark** [comment]
After about half an hour, here is my first start:
<img width="1301" alt="Screenshot 2024-02-03 at 6 31 46 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/92736704/6e6cdc8a-2423-411d-835a-62bed7f93bdb">
I'm going to try and a few more pages that link to other frames. The FAQ and Github buttons are subject to change, both in position and whether or not the github button will be there. I just think it's a good starting point

**Comment by MuellMark** [comment]
After another half an hour, I've added anther frame and a link back to our github. The frames go back and forth from one another and I've added another section to the home page. I'll probably add some more details and then look into the backend side of this project

**Comment by MuellMark** [comment]
I've added a 3rd frame and made an outline for the schedule output could look like. It's still incomplete, but I will come back to it later today or tomorrow. In the mean time, here are some things that could be worked on for the prototype:

- Making it more pleasing to look at. I don't have the best eye for what a "good" website is, so if someone wants to edit the colors or format, that would be awesome!
- A loading page that connects the frames together
- another button for detailing the requirements for the csv's
- making it look ok on mobile. This is very low priority, as I dont think many people store csv's on their phone, but it still should'nt look terrible.

**Comment by colbySullivan** [comment]
I tried finding a streamlined way that we could convert our Figma prototypes to HTML code through plugins. After 30 minutes I tinkered with both Anima and Siter.io. The UI of Anima is good and it fits our requirements but it does have a require subscription so that one is ruled out. Next I used Siter.io which still requires some extra work to get running but if successful I will post the code into my branch.

**Comment by colbySullivan** [comment]
I converted the prototype that we have in Figma to HTML using the Figma to Code plugin. We are also able to convert it into other formats such as React but I many messed with the HTML previewer in VSCode. I pushed them to my branch if anyone wants to check them out.
https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode

**Comment by MuellMark** [comment]
I'm going to keep working on the the generated schedule in Figma to try and come up with a prototype for how it could be formatted on the site. I might make a few different variations that we can look over whenever we meet up again.

**Comment by MuellMark** [comment]
I have the first draft of a schedule created, which looks like this:
<img width="475" alt="Screenshot 2024-02-04 at 4 26 49 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/92736704/5a0fc907-2b70-468f-b333-284b8cd37def">
This is a very bare bones example and it gets the information across, but I have and idea for another schedule that would look a lot better than I'm about half way through making.

On top of this, I realized there needs to be a centralized document for specifying the inner workings of the scheduler, and what the course abbreviations are. After I'm done with my new schedule idea, I'll create that document for us

**Comment by MuellMark** [comment]
I've created a new schedule format where it places a heavier emphasis on the columns. It only has the courses listed out, but hovering over the course has an overlay of the professor's name. This looks cleaner in my opinion, and it lets us add additional info like the course number in the overlay. It looks like this:
<img width="1239" alt="Screenshot 2024-02-04 at 5 03 25 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/92736704/a1ea6dd9-9921-4246-9b1c-d1977e3b3e81">
I'm going to make a general info doc in our google drive, and I'll make a different issue to document it since I don't want to clog up this thread with unrelated info

**Comment by katenguyen10** [comment]
After doing some research/learning about Figma, I am going to continue working on the prototype created by Mark and complete some of the tasks he specified above.

**Comment by katenguyen10** [comment]
Making the prototype look more visually appealing, experimenting with the various features that could be beneficial for our application

**Comment by MuellMark** [comment]
While Figma was a good starting point, Yahyah has been manually putting in CSS and HTML code for the front end of our site, rendering Figma obsolete (for us). I;m closing this as not planned, as we no longer need a proper Figma prototype
