### ISSUE TITLE
Create the Poster

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#65]
This issue is to document any work done on the poster. As we're working we can start adding to the poster whenever we get burnt-out on coding or whatnot

The poster can be found [here.](https://docs.google.com/presentation/d/1Iy62gbXeHg4z3HR07fQSkCRSeQz75vPONVf_uA1JnOQ/edit?pli=1#slide=id.p) It's already formatted to be the correct size.

**Comment by MuellMark** [comment]
As I mentioned in #66, My last half hour was used to work on the poster. I added in the abstract as a starting point. I also added some starting words for the python script. Finally, I also added in section headers for things that I think will be needed.

**Comment by katenguyen10** [comment]
Going to start working on the poster

**Comment by katenguyen10** [comment]
It's been 45 minutes and I have started explaining the create csv page and restructuring the poster layout. This is what I have so far. 
![Screenshot 2024-04-07 173823](https://github.com/MuellMark/Course-Scheduler/assets/89275901/15b16a7d-8886-410d-8801-827c9bddff17)
``

**Comment by katenguyen10** [comment]
Coming back and continuing to work on the poster

**Comment by katenguyen10** [comment]
It's been 30 minutes and I have been adding pictures to the poster and going to figure out what other info to put in the sections of the poster

**Comment by katenguyen10** [comment]
Still working on the poster after 30 minutes. Discussing with my group what addtional sections we should prioritize putting on the poster

**Comment by katenguyen10** [comment]
After 30 minutes I have included sections explaining the linear programming aspect of the project and some useful features. I will continue discussing with my teammates if they feel these are necessary to include or not

**Comment by Hamdally** [comment]
Poster has been complete, so this isn't needed anymore.

Poster:
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/ddff01cb-4fab-45ba-a87b-928a0247eccb)
