### ISSUE TITLE
HOME: Design and Implementing

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#69]
Separating these by each webpage should help keep our issues more organized and not stack issues from different pages onto one.

**Comment by Hamdally** [comment]
Current Look: 
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/088661c5-ed20-4fb8-990d-51d237f50d27)

Tasks:

- Touch up description
  - Maybe make longer
- Add picture 
  - Still debating on what we should showcase, a final product?
- Continue editing design
 - Move text to left side of screen to accommodate the picture and other designs

**Comment by katenguyen10** [comment]
For 30 minutes I have been working on adding a picture next to the description. I am putting a placeholder one for now until we get a real outputted result of a possible schedule and then I will put that there

**Comment by katenguyen10** [comment]
For 30 minutes I have been working on the design. I put the placeholder picture to the right, revised the description to be less complex/more simplified. Might add a button underneath to make initial "getting started" pop out to the users

**Comment by katenguyen10** [comment]
After 30 minutes, this is what I have done with the home page. 
![Screenshot 2024-03-10 202743](https://github.com/MuellMark/Course-Scheduler/assets/89275901/42dfb433-fc18-44f8-ab2d-602ba4cd42db)

**Comment by katenguyen10** [comment]
To dos: 
1. Center "Get Started" button
2. Resize images
3. make all pages responsive to resizes

**Comment by katenguyen10** [comment]
After 30 minutes, I moved the button and have been researching how to make it responsive to resizes. Think I need to use @media in CSS but will look further into it. Need to make a new style for the images because the github image is currently taking the default settings from the final result image

**Comment by katenguyen10** [comment]
After 30 minutes, the github icon is fixed, but now the sizing of the results picture is acting up. It won't float right which is odd because it was working before

**Comment by katenguyen10** [comment]
After 15 minutes I realized I had the div container set to div style instead of div id. It is fixed now. Here is what the homepage looks like now. 
![Screenshot 2024-03-22 104057](https://github.com/MuellMark/Course-Scheduler/assets/89275901/359b7f27-26c4-4154-85c2-1171bfc9bf78)

**Comment by Hamdally** [comment]
For the past 30 minutes, I have been trying to push the content under the header image. But it seems like I might need to mess with the containers as it is causing everything to be pushed down as it is all using the same css style. So I will mess around and make it more aesthetically pleasing.

**Comment by katenguyen10** [comment]
to dos for 3/25:

1. fix containers/design
2. remove faculty names from picture

**Comment by katenguyen10** [comment]
GOing to start working on these

**Comment by katenguyen10** [comment]
after 30 minutes, the spacing of texts (fix containers task) has been fixed, I have removed the faculty names from the picture, and the create schedule button was put in the nav menu again

**Comment by Hamdally** [comment]
Most of the tasks are done, but the page is not responsive completely. So I will be working to make sure that the page looks good on any screen.

**Comment by Hamdally** [comment]
Page has been updated and has been made responsive:
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/e709d2ee-cab6-414e-89e1-c43be3236e6d)

**Comment by Hamdally** [comment]
Homepage has been completed. If there are any updates we want to do, we can reopen issue. 

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/739ae7c5-a3df-4611-adc6-b73ef02f972b)
