### ISSUE TITLE
FAQ: Design and Implementing

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#70]
Separating these by each webpage should help keep our issues more organized and not stack issues from different pages onto one.

**Comment by Hamdally** [comment]
Current Look:
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/03751848-5281-48c0-8f85-9e7311b243a7)

Tasks:

- Come up with questions and answers
- Who is this targeted against? 
- Add stuff to right and left? 
  - Or move table to left and add something to right to balance out 
- Clean Up Overall Design

**Comment by katenguyen10** [comment]
For some reason, wehn I add a picture to the right of the FAQ dropdown section, it squishes when they are closed. When one of the questions is opened, then it expands to its full width. For 30 minutes I have been trying to figure out how to fix this so that it is always at its full width.

**Comment by katenguyen10** [comment]
Going to see how to fix the faq dropdown section so that it is not squished

**Comment by katenguyen10** [comment]
After 30 minutes I figured it out. I was over complicating it. The CSS settings for the FAQ container had it set to a max width, but not a default width when not expanded.

**Comment by Hamdally** [comment]
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/d19abb39-9cb0-4007-9932-04677d8e90fa)

FAQ page has been updated, now it is time to work on the responsiveness of the webpage to make sure it is updated to the screen size.

**Comment by Hamdally** [comment]
The webpage is now responsive and when it  is half screen or smaller, the image will disappear, so it won't affect the rest of the table. Check out the image below to see what I mean.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/66904c2e-f201-4ddf-bc85-3749b2954cb8)

**Comment by Hamdally** [comment]
FAQ page has been complete. If any works has to be done, we can reopen issue.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/315ababa-7f90-46fa-95ec-425ee605facc)
