### ISSUE TITLE
CREATE CSV: Design and Implementing

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#71]
Separating these by each webpage should help keep our issues more organized and not stack issues from different pages onto one.

**Comment by Hamdally** [comment]
Current Look:
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/0aaec775-034f-4acc-915b-f4d8e8788509)

Tasks:

- Change the check box to include the name of the day of the week for unavailable times
- Spread out to fit the webpage
- Center buttons
- Change checkboxes to say specific days/times
- Add human error checks
  - Make it so the user cannot remove the last row. At least one row should be available 
  - Make it so the user cannot submit an empty file. Have it so each row and item must be filled
- Clean up design
  - Need to make table responsive so it can accommodate different screen sizes.
  - Remove redundant and unnecessary buttons

**Comment by Hamdally** [comment]
Tasks:
- Change the check box to include the name of the day of the week for unavailable times
- Spread out to fit the webpage
- Center buttons
- Change checkboxes to say specific days/times
- Add human error checks
 - Make it so the user cannot submit an empty file. Have it so each row and item must be filled
- Clean up design
  - Need to make table responsive so it can accommodate different screen sizes.
  - Remove redundant and unnecessary buttons
  - Make webpage more appealing.

Completed:

 - Make it so the user cannot remove the last row. At least one row should be available
 
 
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/399eb0ad-0cd6-4e5d-85a3-93aa9d3e2b0a)

**Comment by Hamdally** [comment]
Was successfully able to implement both error checks. Just need to add error check to CSV. I will push my stuff to main for others to see.

**Comment by katenguyen10** [comment]
For 30 minutes, I have been working on the task of making the table and all buttons functional, removing redundant/unnecessary buttons, etc

**Comment by katenguyen10** [comment]
For part of the CSV files inputting after the unavailable times, the courses that follow are all the ones that conflict with the course being added. For 30 minutes I have been trying to figure out the best way to go about adding this in the table. Right now we have it as adding another column to the right but it is not visually appealing and also doesn't make sense to the user.

**Comment by katenguyen10** [comment]
For 30 minutes I have been trying to make the add conflicting courses functionality make more sense. I removed the button from the table itself and am figuring out how to make the table resize, becuase with each added conflicting course, the table squishes and eventually runs off the page. Going to look into a side scroll maybe if I can't figure out the vertical aspect

**Comment by katenguyen10** [comment]
After 30 minutes I have implemented a scroll into each table so that it doesn't run off the page anymore. However, before it reaches the width to activate it, the table headers get squished which I don't really like the look off. Need to look into fixing that so the scroll prevents the squishing.

**Comment by katenguyen10** [comment]
Going to match design aspects to rest of webpage

**Comment by katenguyen10** [comment]
After 30 minutes I have updated the look of some design aspects in this page, as well as the dynamic faculty csv page.

**Comment by katenguyen10** [comment]
We need to add an image to serve as a key for the unavailable times checkboxes.

**Comment by katenguyen10** [comment]
I am going to try and fix the github icon on this page. I want it to be at the bottom of the page. Right now it is in a fixed position to where it overlaps on top of other buttons when we scroll

**Comment by katenguyen10** [comment]
After 30 minutes, I manually put it underneath all items on the page, but it is not conforming to the other css settings I have set. Still trying to fix this

**Comment by katenguyen10** [comment]
It has been 30 minutes and I still couldn't get it to work so I started to play around with fixing the style of the unavailable times checkboxes. Want to remove the border and change the text of the times.

**Comment by katenguyen10** [comment]
Coming back after pausing yesterday, going to work on the border and text of unavailable times and fix the style of the add new course button

**Comment by katenguyen10** [comment]
After 35 minutes, I have changed the style of the table, moving the buttons within the table. Think this makes it more organized. The add new course one isn't working so I am trying to figure that out.

**Comment by katenguyen10** [comment]
After 30 minutes I finished changing the styles of both tables, this is what I have so far. The add row functionality still needs to be fixed. 
![Screenshot 2024-03-24 100707](https://github.com/MuellMark/Course-Scheduler/assets/89275901/282f8fed-cf53-4ee3-9d61-47d2fb5f4edd)

**Comment by katenguyen10** [comment]
Going to work on changing the fieldset in unavailable times now.

**Comment by katenguyen10** [comment]
It's been about 15 minutes and nothing seems to be working. I don't want to break the code, so I will discuss with Colby since he made this to see if he knows how to do it.

**Comment by katenguyen10** [comment]
Coming back after taking a break. I will be implementing the hover button function (when hovering over a button, shows it is selected) so that people know it is a button they are clicking.

**Comment by katenguyen10** [comment]
After 30 minutes, I have implemented the hover function on all buttons on the page. I resized text input types and also the size of certain cells of the tables.

**Comment by katenguyen10** [comment]
To dos for 3/25 week:

1. fix add new course drop down
2. get rid of squishing of all fields (add scroll to each cell)
3. put unavailable times in faculty table
4. change courseid from dropdown to textbox
5. remove add to firebase (later, not yet but eventually)

**Comment by katenguyen10** [comment]
also need to make an in between page to give option of importing already created csv or create a new one

**Comment by katenguyen10** [comment]
I'm going to start working on this to do list

**Comment by katenguyen10** [comment]
It's been 30 minutes and I fixed the add new course style button. I've been researching how to add horizontal scrollbars to an individual cell but it hasn't worked. Going to keep working on figuring this out.

**Comment by katenguyen10** [comment]
Things left to do: 
1. add scroll to each cell
2. put unavailable times in faculty table
3. remove add to firebase
4. comment code
5. error check for save as csv

**Comment by katenguyen10** [comment]
It's been 30 minutes and I added the unavailable times to the faculty table, resizing all cells in table. I added the error code but it doesn't seem to be working even though I used the same code as for course table. Need to speak with Yahya since he wrote the original code.

**Comment by katenguyen10** [comment]
Coming back and going to reattempt adding scroll in the unavailable times cell

**Comment by katenguyen10** [comment]
It has been 30 minutes and I tried different methods but they don't seem to be working. I took out the scroll for the whole table thinking it might've been going against that code, but it didn't work. It is not common to add scroll to a singular cell, usually just to the entire table so I am just going to put that code back in for now. I will discuss with my other teammates if they have an idea.

**Comment by katenguyen10** [comment]
going to work on the style of the inbetween page

**Comment by katenguyen10** [comment]
After 30 minutes, this is what I've done with it. There is no functionality on the import button yet until we make that page
![Screenshot 2024-03-31 084835](https://github.com/MuellMark/Course-Scheduler/assets/89275901/6f75a477-d76d-4ec3-98e7-4444ca9fbe68)

**Comment by katenguyen10** [comment]
Coming back and going to keep working on create csv page, add buttons to lead to final results page that i will work on also

**Comment by katenguyen10** [comment]
It's been thirty minutes and I have added a button that will be used to navigate to the next step of the create schedule process. Right now it just directs to the final results page, but we will make a page that takes in the CSV files and then that page will create the final scheduling. Made small edits to make the design consistent and I also made a few edits in the final results page.

**Comment by katenguyen10** [comment]
To do:
1. for faculty table, combine classes with enter courses (move unavailable times to left

**Comment by katenguyen10** [comment]
starting to work on this task

**Comment by katenguyen10** [comment]
It's been 30 minutes and I fixed the faculty table. I am working on the import csv page. Since we switched to flask, there are some small syntax changes, specifically with referencing other pages through linked buttons. Need to figure out how we did it.

**Comment by katenguyen10** [comment]
It's been another 30 minutes and I have figured out how to reference other pages through the app.py page. I have also been working on the import csv page.

**Comment by katenguyen10** [comment]
After 30 minutes this is what I have for the import csv page. What needs to be done is have it to where once the user hits upload, it will lead to the tool that makes the schedule
![Screenshot 2024-04-07 141317](https://github.com/MuellMark/Course-Scheduler/assets/89275901/960530fe-dd79-4a0a-9976-8d22045aeeab)

**Comment by katenguyen10** [comment]
merged changes into my branch lead to merge conflicts that I am working on fixing right now

**Comment by katenguyen10** [comment]
Took me 15 minutes to resolve all conflicts and fix the changes it imposed in vs code

**Comment by Hamdally** [comment]
This page is mostly done. There are still a few design changes we need to make, but the structure of the code and page will not be changing. We also need to make the webpage more responsive to smaller screens.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/069c6088-6ed3-4501-a636-32a0dac572d1)

**Comment by Hamdally** [comment]
The Create CSV page has been completed and this issue is not needed anymore.
