### ISSUE TITLE
How To Guides: Design and Implementing

### ISSUE THREAD

**Issue by Hamdally** [MuellMark/Course-Scheduler#72]
Separating these by each webpage should help keep our issues more organized and not stack issues from different pages onto one.

**Comment by Hamdally** [comment]
Current Look:
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/9cca9845-78fa-4b37-a18e-9193e7bb0642)


Tasks:

- Start documentation 
- Start making Guides

**Comment by Hamdally** [comment]
New Task - Make design of webpage cleaner and nicer.

**Comment by Hamdally** [comment]
Completed the task to update the design of the page. 
![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/777821be-f3f8-461b-9b3b-32c43d2ab50e)

**Comment by katenguyen10** [comment]
I will begin working on the documentation for our application. This will include an explanation of what it is and how to use it.

**Comment by katenguyen10** [comment]
It has been 30 minutes and I have created the doc, and begun writing about how to use it.

**Comment by katenguyen10** [comment]
Coming back to this and will continue documentation

**Comment by katenguyen10** [comment]
It has been 30 minutes and I have been working on the course schedule documentation. Here is the link to access it: [https://docs.google.com/document/d/1Krq0oJCur0b5WY7SfczM0wxV_OzMgpXvl1veBNE6grc/edit?usp=sharing](url)

**Comment by katenguyen10** [comment]
It has been another 30 minutes of working on the documentation. I have completed the explanation of what the course schedule is and its functionality and am working on the steps of how to use this applciation.

**Comment by katenguyen10** [comment]
For 30 minutes, I have added to the documentation about linear programming and csv files. I felt these would be helpful to include to understand the components of the application and how they were included.

**Comment by katenguyen10** [comment]
For the last 30 minutes, I have been documenting how to use the application. I'm calling it for the night after completing my 5 hours, but will return to this more later this week. It obviously is missing some portions as we have not implemented all of the functionality into our application yet.

**Comment by Hamdally** [comment]
I will create a new issue for manuals and documentation, but the page has been completed. If there are any updates, we can reopen the issue.

![image](https://github.com/MuellMark/Course-Scheduler/assets/88158644/f6daa4f4-d44d-4179-bf7d-edd3e1d395e4)
