### ISSUE TITLE
Watching Figma basics video (sent from Dr. Anthony)

### ISSUE THREAD

**Issue by katenguyen10** [MuellMark/Course-Scheduler#8]
I've been watching this video for about 30 minutes to get a better understanding of how to use Figma. This is helpful for us to learn about possible features and things that can be employed in our website. It will also give me a better idea of all of the requirements we would be able to include using the tool.

**Comment by katenguyen10** [comment]
I've finished the video and I've discovered some features that would be very beneficial/accomplish the requirements we had set for our application. I am going to go into Figma and start experimenting with what I learned

**Comment by MuellMark** [comment]
I'm closing this issue because anything that could come from this can be put into #1
