### ISSUE TITLE
FINAL_SCHEDULE_RESULT: Design and Implementation

### ISSUE THREAD

**Issue by katenguyen10** [MuellMark/Course-Scheduler#89]
This will be for the final result, outputted schedule page.

**Comment by katenguyen10** [comment]
For 30 minutes I have been working on the design of the outputted final schedule. I put the data into a table to organize it better

**Comment by katenguyen10** [comment]
After 30 more minutes, I have continued adding to the design. Adding some buttons that I will add functionality to later.

**Comment by katenguyen10** [comment]
For 30 minutes I have continued making the page look more appealing and making it easy for the user to understand.

**Comment by katenguyen10** [comment]
I have been trying to take the result schedule and place it on the home page. For 30 minutes I have been trying to figure out how to do this, because typically I can simply set the img src as the image address, but I can't do that directly from my downloads.

**Comment by Hamdally** [comment]
@colbySullivan @MuellMark I was wondering if we were implementing the ability to change courses after creating the csv. What was the idea? And what would it look like in the front-end? We can talk about this in class?

**Comment by Hamdally** [comment]
Page is not used. So closing issue
