### ISSUE TITLE
Create a page to create a CSV file

### ISSUE THREAD

**Issue by MuellMark** [MuellMark/Course-Scheduler#9]
The CSV creator page should be broken up into 2 separate pages:

1. Adding all of the courses:
- There should be a drop down that lists all of the CS and Math courses with an option to add a new course
- the abbreviation for the course, autofilled if it's a course already in drop down
- a checkbox if it's a 4 contact hour course (also autofilled)
- the number of sections offered
- a check box for all of the times to select when the course cannot be taught

2. Adding all of the corresponding faculty courses:
-  There should be a row for all of the courses combos with sections
- each row will have a text box for the faculty's name
- a checkbox boolean for whether or not they need to teach out of the primetime
- and also a check box for all of the times to select when the faculty cannot teach

**Comment by colbySullivan** [comment]
I started on a simple template for trying to create an HTML form page that passes arguments to a pyscript. It seems feasible to scale up to what we want and I supplied a link below so we could export the newly created data to a CSV.
https://datatofish.com/export-dataframe-to-csv/

**Comment by colbySullivan** [comment]
I think I found another great resource outline for importing and outputting CSVs in pyscript using Pandas. Below I attached an example from the official pyscript GitHub repository that gives an simple example of taking a raw CSV file from within the same repository. The site also lets you preview your work as you go.
https://pyscript.com/@examples/pandas/latest

**Comment by colbySullivan** [comment]
Would it be worth trying to find a list of all classes and their acronym/id or should we dynamically add new courses based on responses? If we do it dynamically we could also organize them based on course type to make it more user friendly. Overall I feel like this is something that we might need to sit down and make a plan for.

**Comment by MuellMark** [comment]
@colbySullivan I have part of an answer for this. The acronyms aren't from the school, they were made by me for the sake of convenience for working with the code. We could have a pool of names that we call from and if they aren't in the set we can add courses. To do this we may need a database to store said course info.

Another option is altering the naming scheme to go in line with Southwestern's course ID's. This would take some changes to the original Python script, but it's also doable. This is definitely something we should discuss going forward.

**Comment by colbySullivan** [comment]
I'm going to start work on a page that dynamically creates a table for adding a new class restriction. And I'll try and add a download CSV function.

**Comment by colbySullivan** [comment]
Got a basic scalable page that can generate a table for class restrictions. It uses basic javascript to create a new row every time you press the add button. The unavailable times are broken but should be an easier fix. I am going to take a break for some dinner but I might try and tackle the download button later.
![image](https://github.com/MuellMark/Course-Scheduler/assets/88957296/a53e3b9f-7d0d-4a9a-8076-23612bcf1a18)

**Comment by colbySullivan** [comment]
Going to start searching for some source code that downloads a CSV from a file using JavaScript or Pyscript in PHP.

**Comment by colbySullivan** [comment]
Got it to download the CSV into the same format as the table but it is not grabbing the user inputs. Instead it is grabbing the literal HTML command. Will need to mess with it some more to get it fixed but I am done for the night.
![image](https://github.com/MuellMark/Course-Scheduler/assets/88957296/40f6e157-6d4a-493a-abe3-990eb955851f)

**Comment by colbySullivan** [comment]
Starting to finalize the source file which holds most if not all of our temp webpages. In the next half an hour I hope to have them all documented and connected via hyperlinks.

**Comment by colbySullivan** [comment]
I got everything organized and knocked out the view_csv.php page which essentially allows you import a csv from one page and view it in another. I'm going to keep working on the down function before I merge it in.

**Comment by colbySullivan** [comment]
Cleaned up the formatting for the dynamic page. Going to ask in our meeting if this is how we want it to look and function before I delegate more time to fixing the download functionality. All else looks good so I'm going to merge in the couple minutes.

**Comment by colbySullivan** [comment]
I am starting work on the faculty restriction page.

**Comment by colbySullivan** [comment]
I have a decent outline for the faculty restriction but I am working on implementing a button that lets you add individual columns for each row for when I faculty member teaches multiple classes. I am also working on fixing the table to CSV function.

**Comment by colbySullivan** [comment]
I almost have a working copy for a new way to do the faculty restrictions page. I also cleaned up our JS scripts into individual files so that they are accessible to multiple pages such as the courses and faculty pages.

**Comment by colbySullivan** [comment]
I took a break to eat but I am going to get back to work on saving forms to CSVs.

**Comment by colbySullivan** [comment]
I have gotten everything from the form correctly taking the inputs and putting them into a CSV except for the days unavailable check boxes. I think I have a fix and with post a picture and a merge request once its done.

**Comment by colbySullivan** [comment]
I hit a large road block where it will download a complete CSV with the correct values but only the first row. I found a promising result with the queryselectorall method.
https://stackoverflow.com/questions/10777684/how-to-use-queryselectorall-only-for-elements-that-have-a-specific-attribute-set

**Comment by colbySullivan** [comment]
I had to drive home so this a bit delayed but I got the CSV download working for multiple rows and consistently. I'll commit it in tomorrow after our meeting.
![image](https://github.com/MuellMark/Course-Scheduler/assets/88957296/3faf5596-9c6a-46d7-abca-f2af21fa6809)
![image](https://github.com/MuellMark/Course-Scheduler/assets/88957296/f3642850-2806-4202-aa96-3110256151db)

**Comment by colbySullivan** [comment]
I think I found a easier way to add new columns to an existing row so I am going to start on that.

**Comment by colbySullivan** [comment]
I got a method working for the faculty restrictions page but I still need to set up the download script. I have a meeting now so I start on that over the weekend.
<img width="1582" alt="Screenshot 2024-02-23 at 3 07 01 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/88957296/f02a5c03-9417-4fab-8203-76e5e3be6f3a">

**Comment by colbySullivan** [comment]
I am going to start working on finalizing my branch and then merging it into main. The main tasks I have left are adding a class button for both the restriction CSVs.

**Comment by colbySullivan** [comment]
I just finished cleaning up some loose ends and adding some TODOs for future task. The merge had minimal conflicts and went very smoothly.

**Comment by colbySullivan** [comment]
I am going to start working on taking the inputs from the dynamic table file and putting them into the firebase database. I am going to be using the CourseID as the key but that can be changed.

**Comment by colbySullivan** [comment]
Currently still working on getting the data to map correctly to the database. I have successfully gotten it to grab it from the form using querySelector but I am specifically having trouble with the CourseID select form value which I am using as a key.

**Comment by colbySullivan** [comment]
I got it a working copy that takes in all the inputs except for unavailable times. I put in all the references I use and will continue to make it a little more scalable for when we change the dynamic form.
<img width="1196" alt="Screenshot 2024-02-27 at 7 47 54 PM" src="https://github.com/MuellMark/Course-Scheduler/assets/88957296/2fe009e2-daae-4d26-b4cf-333f69e52cfd">

**Comment by colbySullivan** [comment]
I have attempt to move the database integration script into its own java script file but I have had little to no luck. I am going to abandon it for now since it is working in the main dynamic table file. I am going to now clean up some issues and add some more documentation to varies files.
